FROM maven:3.8.4-openjdk-8 AS builder

WORKDIR /app

COPY . .

RUN mvn -pl web-ui,tunnel-server package -DskipTests

FROM openjdk:8-jdk-alpine

LABEL maintainer="梦想歌 <shiyindaxiaojie@gmail.com>"
LABEL version="1.0.0"

ENV HOME "/app"
ENV TZ "Asia/Shanghai"
ENV LANG "C.UTF-8"
ENV XMS "1g"
ENV XMX "1g"
ENV XSS "256k"
ENV GC_MODE "CMS"
ENV USE_GC_LOG "Y"
ENV USE_HEAP_DUMP "Y"
ENV USE_LARGE_PAGES "N"
ENV SERVER_PORT "8080"
ENV NACOS_CONFIG_ENABLED "false"
ENV NACOS_CONFIG_SERVER_ADDR "localhost:8848"
ENV NACOS_CONFIG_NAMESPACE "middleware"
ENV NACOS_CONFIG_GROUP "arthas"
ENV NACOS_CONFIG_USERNAME "nacos"
ENV NACOS_CONFIG_PASSWORD "nacos"

WORKDIR $HOME

COPY --from=builder /app/tunnel-server/target/arthas-tunnel-server-3.6.7-fatjar.jar ./app.jar
COPY --from=builder /app/tunnel-server/target/classes/application.properties ./
COPY --from=builder /app/entrypoint.sh ./
RUN chmod +x entrypoint.sh

EXPOSE $SERVER_PORT

ENTRYPOINT ["./entrypoint.sh"]